# This single codebase performs generating of subject, verb, article, adjective, and noun, plus sentence assembly.
# True microservices would have separate codebases, but for our purposes a single codebase is fine.
# Run by opening 6 separate command prompts:
# java -jar -Dspring.profiles.active=subject lab-4-eureka-client-solution-0.0.1-SNAPSHOT.jar
# java -jar -Dspring.profiles.active=verb lab-4-eureka-client-solution-0.0.1-SNAPSHOT.jar
# java -jar -Dspring.profiles.active=article lab-4-eureka-client-solution-0.0.1-SNAPSHOT.jar
# java -jar -Dspring.profiles.active=adjective lab-4-eureka-client-solution-0.0.1-SNAPSHOT.jar
# java -jar -Dspring.profiles.active=noun lab-4-eureka-client-solution-0.0.1-SNAPSHOT.jar
# java -jar -Dspring.profiles.active=sentence lab-4-eureka-client-solution-0.0.1-SNAPSHOT.jar

---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

  instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


server:
  port:  ${PORT:${SERVER_PORT:0}}   # Select any available port if neither port nor server port are specified.

